# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/cn"
  title = "峇冬丁宜圣母圣名堂"

[ta]
  languageCode = "ta"
  contentDir = "content/ta"
  title =  "மரியாளின் தூய நாம தேவாலயம் பெர்மாத்தாங் திங்கி"

[zh.params]
  description = "欢迎来到圣母圣名堂！ 我们的教堂坐落在巴冬丁宜，距离居林、爪义、武吉淡文南北大道不远。"

[[zh.menu.main]]
  name = "首页"
  url = "#about"
  weight = 10

[[zh.menu.main]]
  name = "帖子"
  url = "#posts"
  weight = 20

[[zh.menu.main]]
  name = "精选"
  url = "#projects"
  weight = 30

[[zh.menu.main]]
  name = "关于"
  url = "#publications"
  weight = 40

[[zh.menu.main]]
  name = "联络"
  url = "#contact"
  weight = 50

[[zh.menu.main]]
  name = "圣事"
  url = "sacraments"
  hasChildren = true
  weight = 60

[[zh.menu.main]]
  parent = "圣事"
  name = "领洗圣事"
  url = "sacraments/baptism"

[[zh.menu.main]]
  parent = "圣事"
  name = "圣体圣事"
  url = "sacraments/communion"

[[zh.menu.main]]
  parent = "圣事"
  name = "坚振圣事"
  url = "sacraments/confirmation"

[[zh.menu.main]]
  parent = "圣事"
  name = "婚姻圣事"
  url = "sacraments/matrimony"

[[zh.menu.main]]
  parent = "圣事"
  name = "和好圣事"
  url = "sacraments/reconciliation"

[[zh.menu.main]]
  parent = "圣事"
  name = "病人傅油"
  url = "sacraments/anointing"

[[zh.menu.main]]
  parent = "圣事"
  name = "圣秩圣事"
  url = "sacraments/holy-orders"

[[zh.menu.main]]
  name = "组织"
  url = "groups"
  hasChildren = true
  weight = 70

[[zh.menu.main]]
  parent = "组织"
  name = "基信组"
  url = "groups/bec"

[[zh.menu.main]]
  parent = "组织"
  name = "神恩复兴小组"
  url = "groups/charismatic-prayer-group"
