# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
### Mandarin menu
[zh]
  languageCode = "zh-Hans"
  contentDir = "content/cn"
  title = "峇冬丁宜圣母圣名堂"

[zh.params]
  description = "欢迎来到圣母圣名堂！ 我们的教堂坐落在巴冬丁宜，距离居林、爪义、武吉淡文南北大道不远。"

[[zh.menu.main]]
  name = "关于"
  url = "#about"
  weight = 10

[[zh.menu.main]]
  name = "堂讯"
  url = "#accomplishments"
  weight = 20

[[zh.menu.main]]
  name = "圣言反省"
  url = "#posts"
  weight = 30

[[zh.menu.main]]
  name = "天主教资料"
  url = "#projects"
  weight = 40

[[zh.menu.main]]
  name = "活动"
  url = "#talks"
  weight = 50

[[zh.menu.main]]
  name = "刊物"
  url = "#publications"
  weight = 60

[[zh.menu.main]]
  name = "联络"
  url = "#contact"
  weight = 90

#[[zh.menu.main]]
#  name = "圣事"
#  url = "sacraments"
#  hasChildren = true
#  weight = 70

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "领洗圣事"
#  url = "sacraments/baptism"

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "圣体圣事"
#  url = "sacraments/communion"

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "坚振圣事"
#  url = "sacraments/confirmation"

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "婚姻圣事"
#  url = "sacraments/matrimony"

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "和好圣事"
#  url = "sacraments/reconciliation"

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "病人傅油"
#  url = "sacraments/anointing"

#[[zh.menu.main]]
#  parent = "圣事"
#  name = "圣秩圣事"
#  url = "sacraments/holy-orders"

[[zh.menu.main]]
  name = "组织"
  url = "groups"
  hasChildren = true
  weight = 70

[[zh.menu.main]]
  parent = "组织"
  name = "基信组"
  url = "groups/bec"

[[zh.menu.main]]
  parent = "组织"
  name = "神恩复兴小组"
  url = "groups/charismatic-prayer-group"

[[zh.menu.main]]
    name = "灵修"
    hasChildren = true
    weight = 80

[[zh.menu.main]]
    parent = "灵修"
    name = "黄柄隆神父"
    url = "spiritual-column"

### Tamil menu
[ta]
  languageCode = "ta"
  contentDir = "content/ta"
  title =  "HNM Permatang Tinggi"


[[ta.menu.main]]
  name = "முகப்புப்பக்கம்"
  url = "#about"
  weight = 10

[[ta.menu.main]]
  name = "பதிவுகள்"
  url = "#posts"
  weight = 20

[[ta.menu.main]]
  name = "அம்சங்கள்"
  url = "#projects"
  weight = 30

[[ta.menu.main]]
  name = "பற்றி"
  url = "#publications"
  weight = 40

[[ta.menu.main]]
  name = "தொடர்பு"
  url = "#contact"
  weight = 50

[[ta.menu.main]]
  name = "சடங்குகள்"
  url = "sacraments"
  hasChildren = true
  weight = 60

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Baptism"
  url = "sacraments/baptism"

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Communion"
  url = "sacraments/communion"

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Confirmation"
  url = "sacraments/confirmation"

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Matrimony"
  url = "sacraments/matrimony"

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Reconciliation"
  url = "sacraments/reconciliation"

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Anonitng"
  url = "sacraments/anointing"

[[ta.menu.main]]
  parent = "சடங்குகள்"
  name = "Holy Orders"
  url = "sacraments/holy-orders"

[[ta.menu.main]]
  name = "குழுக்கள்"
  url = "groups"
  hasChildren = true
  weight = 70

[[ta.menu.main]]
  parent = "குழுக்கள்"
  name = "BEC"
  url = "groups/bec"

[[ta.menu.main]]
  parent = "குழுக்கள்"
  name = "Charismatic Prayer Group"
  url = "groups/charismatic-prayer-group"
