# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20

[[main]]
  name = "Topics"
  url = "#projects"
  weight = 30

[[main]]
  name = "About"
  url = "#publications"
  weight = 40

#[[main]]
#  name = "Courses"
#  url = "courses/"
#  weight = 50

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 50

[[main]]
  name = "Sacraments"
  url = "sacraments"
  hasChildren = true
  weight = 60

[[main]]
  parent = "Sacraments"
  name = "Baptism"
  url = "sacraments/baptism"

[[main]]
  parent = "Sacraments"
  name = "Communion"
  url = "sacraments/communion"

[[main]]
  parent = "Sacraments"
  name = "Confirmation"
  url = "sacraments/confirmation"

[[main]]
  parent = "Sacraments"
  name = "Matrimony"
  url = "sacraments/matrimony"

[[main]]
  parent = "Sacraments"
  name = "Reconciliation"
  url = "sacraments/reconciliation"

[[main]]
  parent = "Sacraments"
  name = "Anointing"
  url = "sacraments/anointing"

[[main]]
  parent = "Sacraments"
  name = "Holy Orders"
  url = "sacraments/holy-orders"

#[[main]]
#  parent = "Rental"
#  name = "Hall"
#  url = "project/church-hall-rental"
#  weight = 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
